const allData = [
  [` autosave `, ` 個自動儲存 `],
  [` Copy link`, ` 複製連結`],
  [` device.`, ` 設備上下載 Figma Mirror。`],
  [` follower`, ` 關注者`],
  [` following`, ` 正在關注`],
  [` Get embed code`, ` 獲取嵌入程式碼`],
  [` in the main menu.`, `（在主菜單裡面）跳轉到那邊。`],
  [` Learn more`, ` 了解更多`],
  [` learn more`, ` 了解更多`],
  [` on `, ` 發布於 `],
  [` or `, ` 或 `],
  [` projects`, ` 項目`],
  [` Sign up`, ` 注冊`],
  [` started following you`, ` 關注了你`],
  [` team libraries`, ` 團隊元件庫`],
  [` to create your own plugin and manage any plugins currently in development.`, ` 來創建你自己的插件，以及管理在開發中的插件`],
  [` to create your own plugin.`, ` 創建你自己的插件`],
  [` version history`, ` 版本歷史`],
  [` viewers`, `查看者`],
  [` when you choose the annual plan.`, ` 當你選擇年付計劃時。`],
  [`. Please assign a new owner from the team members list before leaving this team.`, `「的創建者。在離開這個團隊之前，請從團隊成員列表中指定一個新的創建者。`],
  [`.`, `。`],
  [`· Edited `, `· 編輯於 `],
  [`』 project. Notifications are encrypted.`, `」項目中的檔案發表評論時，就會收到通知。通知是加密的。`],
  [`(best for 9+ seats)`, `（建議 9 個人以上）`],
  [`(missing)`, `(已丟失)`],
  [`(threads you're involved in)`, `（我參與的主題）`],
  [`/mo.`, `/月`],
  [`←  Everything in Professional, plus`, `←  專業版的所有功能，加上`],
  [`↓ Duplicate`, `↓ 創建副本`],
  [`↓ Install`, `↓ 安裝`],
  [`↩ Enter`, `↩ 換行`],
  [`✓  Centralized teams`, `✓  中心化的團隊`],
  [`✓  Custom file/user permissions`, `✓  自定義檔案/用戶權限`],
  [`✓  Design System Analytics`, `✓  設計系統分析`],
  [`✓  Figma auto-saves your work`, `✓ Figma 自動儲存你的工作`],
  [`✓  Installed`, `✓ 已安裝`],
  [`✓  Invite-only private projects`, `✓  僅限受邀的私人項目`],
  [`✓  Org-wide team libraries`, `✓  全組織的團隊元件庫`],
  [`✓  Private plugins`, `✓  私有插件`],
  [`✓  Sharable team libraries`, `✓  可共享的團隊元件庫`],
  [`✓  Shared fonts`, `✓  共享字體`],
  [`✓  SSO and advanced security`, `✓  SSO 和高級安全`],
  [`✓  Unlimited projects`, `✓  無限制的項目`],
  [`✓  Unlimited version history`, `✓  無限制的版本歷史`],
  [`1 day ago`, `1 天前`],
  [`1 hour ago`, `1 小時前`],
  [`1 year ago`, `1 年前`],
  [`10 days ago`, `10 天前`],
  [`10 hours ago`, `10 小時前`],
  [`10 months ago`, `10 個月前`],
  [`100% – Display at full size`, `100% - 以完整尺寸顯示`],
  [`11 days ago`, `11 天前`],
  [`11 hours ago`, `11 小時前`],
  [`11 months ago`, `11 個月前`],
  [`12 days ago`, `12 天前`],
  [`12 hours ago`, `12 小時前`],
  [`13 days ago`, `13 天前`],
  [`13 hours ago`, `13 小時前`],
  [`14 days ago`, `14 天前`],
  [`14 hours ago`, `14 小時前`],
  [`15 days ago`, `15 天前`],
  [`15 hours ago`, `15 小時前`],
  [`16 days ago`, `16 天前`],
  [`16 hours ago`, `16 小時前`],
  [`17 days ago`, `17 天前`],
  [`17 hours ago`, `17 小時前`],
  [`18 days ago`, `18 天前`],
  [`18 hours ago`, `18 小時前`],
  [`19 days ago`, `19 天前`],
  [`19 hours ago`, `19 小時前`],
  [`2 days ago`, `2 天前`],
  [`2 hours ago`, `2 小時前`],
  [`2 months ago`, `2 個月前`],
  [`20 days ago`, `20 天前`],
  [`20 hours ago`, `20 小時前`],
  [`21 days ago`, `21 天前`],
  [`21 hours ago`, `21 小時前`],
  [`22 days ago`, `22 天前`],
  [`22 hours ago`, `22 小時前`],
  [`23 days ago`, `23 天前`],
  [`23 hours ago`, `23 小時前`],
  [`24 days ago`, `24 天前`],
  [`25 days ago`, `25 天前`],
  [`26 days ago`, `26 天前`],
  [`27 days ago`, `27 天前`],
  [`28 days ago`, `28 天前`],
  [`29 days ago`, `29 天前`],
  [`3 days ago`, `3 天前`],
  [`3 hours ago`, `3 小時前`],
  [`3 months ago`, `3 個月前`],
  [`3 projects`, `3 個項目`],
  [`30-day version history`, `30 天版本歷史`],
  [`4 days ago`, `4 天前`],
  [`4 hours ago`, `4 小時前`],
  [`4 months ago`, `4 個月前`],
  [`5 days ago`, `5 天前`],
  [`5 hours ago`, `5 小時前`],
  [`5 months ago`, `5 個月前`],
  [`6 days ago`, `6 天前`],
  [`6 hours ago`, `6 小時前`],
  [`6 months ago`, `6 個月前`],
  [`7 days ago`, `7 天前`],
  [`7 hours ago`, `7 小時前`],
  [`7 months ago`, `7 個月前`],
  [`8 days ago`, `8 天前`],
  [`8 hours ago`, `8 小時前`],
  [`8 months ago`, `8 個月前`],
  [`9 days ago`, `9 天前`],
  [`9 hours ago`, `9 小時前`],
  [`9 months ago`, `9 個月前`],
  [`A deleted component is still published in the Team Library`, `被刪除的元件仍在團隊庫中發布。`],
  [`a new look`, `更新啦~`],
  [`About us`, `關於我們`],
  [`Accept`, `接受`],
  [`Account settings`, `帳號設定`],
  [`Account`, `帳號`],
  [`Action`, `動作`],
  [`actions`, `滾動動作`],
  [`Activity from other users`, `其他用戶的活動`],
  [`Add a description`, `添加簡介`],
  [`Add a location`, `添加位置`],
  [`Add a project to your favorites to see it here`, `添加項目到你的收藏，就會在此處顯示`],
  [`Add a website`, `添加網站`],
  [`Add another`, `添加更多`],
  [`Add auto layout`, `添加自動佈局`],
  [`Add background behind overlay`, `在疊加後添加背景`],
  [`Add comment (C)`, `添加評論（C）`],
  [`Add Description`, `添加簡介`],
  [`Add Emoji`, `添加 Emoji 表情`],
  [`Add more seats`, `添加更多席位`],
  [`Add new page`, `添加新頁面`],
  [`Add New Property`, `添加新屬性`],
  [`Add new variant`, `添加新變體`],
  [`Add New Variant`, `添加新變體`],
  [`Add new...`, `添加新的…`],
  [`Add or change your team』s logo or icon that appears on the team page and side navigation`, `添加或修改你的團隊的標志或圖標，會出現在團隊頁面和側邊導航`],
  [`Add or change your team』s public handle`, `添加或更改你的團隊的公眾帳號`],
  [`Add team members`, `添加團隊成員`],
  [`Add to favorites`, `添加到收藏`],
  [`Add to library`, `添加到元件庫`],
  [`Add to version history while editing.`, `當編輯時添加到歷史版本`],
  [`Add to version history`, `添加到版本歷史`],
  [`Add your collaborators`, `添加協作者`],
  [`Add/Show comments`, `添加/顯示評論`],
  [`Added`, `已添加`],
  [`Adjust font size`, `調整字號`],
  [`Adjust font weight`, `調整字重`],
  [`Adjust letter spacing`, `調整字距`],
  [`Adjust line height`, `調整行高`],
  [`Admin dashboard`, `管理員儀表盤`],
  [`admin`, `管理員`],
  [`Admin`, `管理員`],
  [`Advanced options`, `高級選項`],
  [`Advanced stroke settings`, `高級描邊設定`],
  [`Advanced stroke`, `高級描邊`],
  [`After creating a team, you can invite others to join.`, `團隊創建完成後，你可以邀請其他人加入。`],
  [`After delay`, `延遲觸發`],
  [`After selecting points…`, `選擇點後…`],
  [`Align bottom`, `下對齊`],
  [`Align center`, `居中對齊`],
  [`Align centers`, `居中對齊`],
  [`Align horizontal centers`, `水平居中`],
  [`Align left/right`, `左/右對齊`],
  [`Align left`, `左對齊`],
  [`Align middle`, `垂直居中`],
  [`Align right`, `右對齊`],
  [`Align top/bottom`, `上/下對齊`],
  [`Align top`, `上對齊`],
  [`Align vertical centers`, `垂直居中`],
  [`Align`, `對齊`],
  [`Alignment and padding`, `對齊和邊距`],
  [`Alignment is now controlled from the auto layout parent frame.`, `現在可以通過自動佈局父畫框來控制對齊。`],
  [`Alignment is now set on the parent frame instead of on each independent object. And objects can be spaced evenly in a click. `, `現在，對齊方式是在父畫框上設定，而不是在每個獨立對象上設定。而且對象可以一鍵平均分布。`],
  [`Alignment`, `對齊`],
  [`All comments`, `全部評論`],
  [`All of your layers adjust the way you expect – no magic, you get full control.`, `你的所有圖層都會按照你期望的方式進行調整 —— 不是什麼魔法，你可以完全控制。`],
  [`All team files`, `所有團隊檔案`],
  [`All team projects`, `所有團隊項目`],
  [`All Templates`, `所有模板`],
  [`All`, `全部`],
  [`Allow Figma to access your local fonts`, `允許 Figma 訪問你的本地字體`],
  [`Allow viewers to copy, share, and export from this file`, `允許查看者複製、分享以及從這個檔案中導出`],
  [`Alphabetical`, `字母順序`],
  [`Alternate Annotation Forms`, `替代注釋形式`],
  [`Alternate Half Widths`, `替代半寬`],
  [`Always open in Desktop App`, `總是在桌面應用中打開`],
  [`Always open in the App`, `總是在應用中打開`],
  [`An error occurred while opening the editor`, `打開編輯器時發生錯誤`],
  [`An error occurred while running this plugin`, `運行這個插件時發生錯誤`],
  [`An unknown error occurred`, `發生未知錯誤`],
  [`and`, `和`],
  [`Angular`, `角度漸變`],
  [`Animate`, `動畫`],
  [`Animation`, `動畫`],
  [`Annual billing only`, `僅限年付訂單`],
  [`Annual plan`, `年付計劃`],
  [`Anyone with the link`, `知道連結的任何人`],
  [`Anyone`, `所有人`],
  [`Are you sure you want to move this project?`, `你確定要移動這個項目嗎？`],
  [`Are you sure?`, `你確定嗎？`],
  [`Arrange`, `排列`],
  [`Arrow tool`, `箭頭工具`],
  [`Arrow`, `箭頭`],
  [`As Typed`, `按輸入`],
  [`Ascending`, `升序`],
  [`Assembling components and styles`, `正在合並元件和樣式`],
  [`Assets`, `資源`],
  [`Author`, `作者`],
  [`Auto height`, `自動高度`],
  [`Auto layout added`, `已添加自動佈局`],
  [`Auto layout alignment`, `自動佈局對齊`],
  [`Auto Layout has`, `自動佈局`],
  [`Auto layout`, `自動佈局`],
  [`Auto width`, `自動寬度`],
  [`Auto`, `自動`],
  [`Back to files`, `返回檔案列表`],
  [`Back`, `後退`],
  [`Background blur`, `背景模糊`],
  [`Background`, `背景`],
  [`Bend tool`, `彎曲工具`],
  [`Best Practices`, `最佳實踐`],
  [`Beta`, `測試`],
  [`Big nudge`, `大微調`],
  [`Billed annually or US$15 / editor / month`, `按年計費，或 15 美元/編輯者/月。`],
  [`Blank canvas`, `空白畫布`],
  [`Blank Presets`, `空白預設`],
  [`Blend Mode`, `混合模式`],
  [`Blog`, `部落格`],
  [`Blur`, `模糊`],
  [`Bold`, `加粗`],
  [`Boolean groups`, `布林組合`],
  [`Boosted by the Figma Team`, `由 Figma 團隊驅動`],
  [`Borders`, `邊框`],
  [`Bottom Center`, `底部中間`],
  [`Bottom left corner radius`, `下左圓角半徑`],
  [`Bottom Left`, `下左`],
  [`Bottom padding`, `下邊距`],
  [`Bottom right corner radius`, `下右圓角半徑`],
  [`Bottom Right`, `下右`],
  [`Bottom`, `下`],
  [`Brainstorming`, `頭腦風暴`],
  [`Brainstorms and sprints`, `頭腦風暴和沖刺`],
  [`Bridge design and code with Variants`, `用變體在設計和程式碼之間架起橋梁`],
  [`Bring forward`, `上移一層`],
  [`Bring to front`, `移到頂層`],
  [`Browse `, `瀏覽 `],
  [`Browse All Plugins`, `瀏覽全部插件`],
  [`Browse all plugins`, `瀏覽所有插件`],
  [`Browse creators`, `瀏覽創作者`],
  [`Browse libraries...`, `瀏覽元件庫…`],
  [`Build fully-responsive components with new Auto Layout updates. Stretch in any direction, control padding independently, and distribute objects evenly—all in an easier to use interface.`, `使用新的自動佈局更新來構建完全響應的元件。在任何方向上拉伸，獨立控制邊距，並在一個更容易使用的界面中均勻地分配對象。`],
  [`can access`, `可以訪問`],
  [`can edit`, `可以編輯`],
  [`Can edit`, `可以編輯`],
  [`can view prototype only`, `僅可以查看原型`],
  [`can view prototypes only`, `僅可以查看原型`],
  [`can view`, `可以查看`],
  [`Can view`, `可以查看`],
  [`Cancel Professional plan`, `取消專業版計劃`],
  [`Cancel`, `取消`],
  [`Cap`, `端點`],
  [`Capital Spacing`, `大寫字母間隔`],
  [`Careers`, `工作機會`],
  [`Case-Sensitive Forms`, `大小寫敏感形式`],
  [`Case`, `大小寫`],
  [`Center`, `居中`],
  [`Centered`, `居中`],
  [`Change email`, `修改信箱`],
  [`Change handle`, `修改帳號`],
  [`Change icon`, `修改圖標`],
  [`Change name`, `修改名字`],
  [`Change Name`, `修改名字`],
  [`Change password`, `修改密碼`],
  [`Change team icon`, `修改團隊圖標`],
  [`Change team name`, `修改團隊名稱`],
  [`Change your team's name`, `修改你的團隊的名稱`],
  [`Change your unique profile handle`, `修改你獨有的個人主頁帳號`],
  [`Changed`, `已修改`],
  [`Changes not yet published`, `未發布的更改`],
  [`Changes saved`, `更改已儲存`],
  [`Character Variant 1`, `字符變體 1`],
  [`Character Variant 10`, `字符變體 10`],
  [`Character Variant 2`, `字符變體 2`],
  [`Character Variant 3`, `字符變體 3`],
  [`Character Variant 8`, `字符變體 8`],
  [`Character Variant 9`, `字符變體 9`],
  [`Character variants`, `字符變體`],
  [`Choose a channel...`, `選擇一個頻道…`],
  [`Choose a plan`, `選擇一個計劃`],
  [`Choose a slack channel to notify whenever someone comments on a file in the 『`, `選擇一個 Slack 頻道，每當有人對「`],
  [`Choose Education`, `選擇教育版`],
  [`Choose Image...`, `選擇圖片…`],
  [`Choose Image…`, `選擇圖片…`],
  [`Choose Organization`, `選擇組織版`],
  [`Choose Professional`, `選擇專業版`],
  [`Choose Starter`, `選擇入門版`],
  [`Choose your team plan`, `選擇你的團隊方案`],
  [`Click + to replace mixed content.`, `點擊 + 來替換多個內容。`],
  [`Click to Select`, `點擊選擇`],
  [`Click`, `點擊`],
  [`click`, `點擊`],
  [`Clip content`, `裁剪內容`],
  [`Close overlay`, `關閉疊加`],
  [`Close when clicking outside`, `點擊空白處關閉`],
  [`code`, `程式碼`],
  [`Code`, `程式碼`],
  [`Collaborate in real time with your team and never worry about your files being up-to-date.`, `與你的團隊實時協作，再也不用擔心你的檔案是不是最新的。`],
  [`Collaboration Features`, `協作能力`],
  [`Collaboration`, `協作`],
  [`Collapse layers`, `折疊圖層`],
  [`Color Burn`, `顏色加深`],
  [`Color conflict`, `顏色衝突`],
  [`Color Dodge`, `顏色減淡`],
  [`Color Styles`, `顏色樣式`],
  [`Color`, `顏色`],
  [`Colors`, `顏色`],
  [`Columns`, `列`],
  [`Combine as Variants`, `合並為變體`],
  [`Comment actions`, `評論操作`],
  [`Comment notification settings`, `評論通知設定`],
  [`Comments`, `評論`],
  [`Communicate clearly on a small scale with these carefully crafted and inspiring icons`, `用這些精心制作的、鼓舞人心的圖標，在小范圍內清晰地交流`],
  [`Community forum`, `社群論壇`],
  [`Community guidelines`, `社群准則`],
  [`Community`, `社群`],
  [`Compare`, `對比`],
  [`Component`, `元件`],
  [`Component updates available`, `元件有更新`],
  [`Components`, `元件`],
  [`Confirm and pay`, `確認並支付`],
  [`Congratulations!`, `干得漂亮！`],
  [`Connected apps`, `已連接的應用`],
  [`Constrain proportions`, `約束比例`],
  [`Constraints and Resizing`, `約束和調整大小`],
  [`Constraints`, `約束`],
  [`Contact a team admin to enable default libraries for your team.`, `聯系團隊管理員，為你的團隊啟用默認元件庫。`],
  [`Contact sales`, `聯系銷售團隊`],
  [`contact sales`, `聯系銷售團隊`],
  [`Contact`, `聯系`],
  [`Content`, `內容`],
  [`Contents Only`, `僅內容`],
  [`Contextual Ligatures`, `上下文連字`],
  [`Continue to Payment`, `繼續支付`],
  [`Continue`, `繼續`],
  [`Contrast`, `對比度`],
  [`Control alignment at the parent level`, `在父級控制對齊`],
  [`Control their access with granular permissons and manage their access in one simple place.`, `通過精細的權限控制他們的訪問，並在一個簡單的地方管理他們的訪問。`],
  [`Copied to clipboard`, `已複製到剪貼板`],
  [`Copy as CSS`, `複製為 CSS`],
  [`Copy as PNG`, `複製為 PNG`],
  [`Copy as SVG`, `複製為 SVG`],
  [`Copy as text`, `複製為文本`],
  [`Copy as`, `複製為`],
  [`Copy email`, `複製信箱地址`],
  [`Copy link to page`, `複製頁面連結`],
  [`Copy Link`, `複製連結`],
  [`Copy link`, `複製連結`],
  [`Copy properties`, `複製屬性`],
  [`Copy/Paste`, `複製/粘貼`],
  [`Copy`, `複製`],
  [`Corner radius`, `圓角半徑`],
  [`Corner smoothing`, `平滑圓角`],
  [`Count`, `邊數`],
  [`Create a Community profile to publish publicly as your org or team`, `創建一個社群主頁，以你的組織或團隊的身份公開發布。`],
  [`Create a Figma Community profile to Like, Follow, and Publish`, `創建 Figma 社群個人主頁，就可以點贊、關注和發布`],
  [`Create a new file to start from scratch. Import a Sketch file, PNG, or JPG by dragging and dropping.`, `創建一個新檔案從頭開始。可以拖拽導入 Sketch 檔案、PNG 或 JPG 檔案。`],
  [`Create a new personal access token`, `創建新的個人訪問令牌`],
  [`Create a Professional Team`, `創建專業版團隊`],
  [`Create a project`, `創建一個項目`],
  [`Create a Team to Publish Components`, `創建一個團隊來發布元件`],
  [`Create a team`, `創建一個團隊`],
  [`Create account`, `創建帳號`],
  [`Create beautiful apps with mockups, templates, and mobile-friendly layouts`, `使用模型、模板和移動友好的佈局創建漂亮的應用程式`],
  [`Create component`, `創建元件`],
  [`Create file in Drafts`, `在草稿中創建檔案`],
  [`Create file`, `創建檔案`],
  [`Create link`, `創建連結`],
  [`Create multiple components`, `創建多個元件`],
  [`Create new color style`, `創建新的顏色樣式`],
  [`Create new effect style`, `創建新的效果樣式`],
  [`Create new project`, `創建新項目`],
  [`Create new team`, `創建新的團隊`],
  [`Create new text style`, `創建新的文本樣式`],
  [`Create profile`, `創建主頁`],
  [`Create project`, `創建項目`],
  [`Create scroll`, `創建`],
  [`Create style`, `新建樣式`],
  [`Create team`, `創建團隊`],
  [`Create teams to share design libraries with collaborators and organize files into Projects`, `創建團隊，與協作者共享設計元件庫，並將檔案存放到項目中`],
  [`Create teams to share design libraries with collaborators and organize files into projects`, `創建團隊，與合作者共享設計元件庫，並將檔案組織成項目。`],
  [`Created by `, `創建自 `],
  [`Created`, `創建時間`],
  [`Creating a connection`, `創建新的連接`],
  [`Creator`, `創作者`],
  [`Creators`, `創作者`],
  [`Crop image`, `裁剪圖片`],
  [`Crop`, `裁切`],
  [`Current file`, `當前檔案`],
  [`Current name`, `當前名稱`],
  [`Current version`, `當前版本`],
  [`Cursor`, `光標`],
  [`Curve`, `曲線`],
  [`Custom size`, `自定義大小`],
  [`Custom`, `自定義`],
  [`Customers`, `客戶`],
  [`Cut`, `剪切`],
  [`Darken`, `變暗`],
  [`Dashes`, `虛線`],
  [`Date created`, `創建時間`],
  [`Date deleted`, `刪除時間`],
  [`dbl-click`, `雙擊`],
  [`Decline`, `拒絕`],
  [`Decoration`, `文本修飾`],
  [`Decrease font size`, `減小字號`],
  [`Decrease font weight`, `減小字重`],
  [`Decrease letter spacing`, `減小字距`],
  [`Decrease line height`, `減小行高`],
  [`Deep select within rectangle`, `矩形內穿透選擇`],
  [`Deep select`, `穿透選擇`],
  [`Default thumbnail restored`, `已恢復為默認封面`],
  [`Delay`, `延遲`],
  [`Delete  forever`, `永久刪除`],
  [`Delete account`, `刪除帳號`],
  [`Delete and heal selection`, `刪除和修復所選項`],
  [`Delete comment`, `刪除評論`],
  [`Delete community profile`, `刪除社群個人主頁`],
  [`Delete Forever`, `永久刪除`],
  [`Delete forever`, `永久刪除`],
  [`Delete page`, `刪除頁面`],
  [`Delete project`, `刪除項目`],
  [`Delete style`, `刪除樣式`],
  [`Delete team`, `刪除團隊`],
  [`Delete version info`, `刪除版本資訊`],
  [`Delete your profile`, `刪除你的個人主頁`],
  [`Delete`, `刪除`],
  [`Deleted `, `刪除於 `],
  [`Deleted`, `已刪除`],
  [`Deleting your profile will remove all your published files, plugins, likes, and follow data from Figma Community and relinquish your profile handle. This action can not be undone.`, `刪除你的個人主頁，將會從 Figma 社群中刪除所有已發布的檔案、插件、點贊和關注數據，並放棄你的個人主頁帳號。此操作無法撤銷。`],
  [`Descending`, `降序`],
  [`Description`, `簡介`],
  [`Design faster with lo-fi mockups, user flows, simple prototypes, and diagrams`, `使用低調的模擬圖、用戶流、簡單的原型和圖表來加快設計速度`],
  [`Design Features`, `設計能力`],
  [`Design on Windows`, `在 Windows 上設計`],
  [`Design System`, `設計系統`],
  [`Design Systems Features`, `設計系統能力`],
  [`Design Systems`, `設計系統`],
  [`Design systems`, `設計系統`],
  [`Design the perfect website with wireframes, mockups, and responsive layouts`, `使用線框、模擬圖和響應式佈局設計完美的網站`],
  [`design`, `設計`],
  [`Design`, `設計`],
  [`Desktop`, `桌面端`],
  [`Detach instance`, `分離實例`],
  [`Detach style`, `分離樣式`],
  [`Details`, `詳情`],
  [`Developers`, `開發者`],
  [`Development`, `開發`],
  [`device.`, ` 設備上。`],
  [`Device`, `設備`],
  [`Diamond`, `菱形漸變`],
  [`Difference`, `差集`],
  [`Disabled`, `已禁用`],
  [`Discover best practices and inspiring examples to design consistently and efficiently`, `發現最佳實踐和鼓舞人心的例子，以實現一致和有效的設計`],
  [`Discover creators`, `發現創作者`],
  [`Discover new techniques through vector art, character designs, and photorealistic renderings`, `通過向量藝術、角色設計和照片逼真的渲染發現新的技術`],
  [`Dismiss`, `忽略`],
  [`Dissolve`, `溶解`],
  [`Distances`, `距離`],
  [`Distribute bottom`, `向下均分`],
  [`Distribute horizontal centers`, `水平中心均分`],
  [`Distribute horizontal spacing`, `水平間距均分`],
  [`Distribute left`, `向左均分`],
  [`Distribute right`, `向右均分`],
  [`Distribute spacing`, `分布間距`],
  [`Distribute top`, `向上均分`],
  [`Distribute vertical centers`, `垂直中心均分`],
  [`Distribute vertical spacing`, `垂直間距均分`],
  [`Do Nothing`, `不用了`],
  [`Do you want to open this file in the Desktop App?`, `你希望一直在桌面應用中打開這個檔案嗎？`],
  [`Document colors`, `檔案中的顏色`],
  [`Don't see a project? Try searching for it.`, `找不到項目？搜索一下試試看。`],
  [`Done`, `完成`],
  [`Downgrade to viewer`, `降級為查看者`],
  [`Download installer to enable local fonts.`, `下載安裝程式以啟用本地字體。`],
  [`Download the latest desktop app`, `下載最新的客戶端應用`],
  [`Download uninstaller to disable local fonts.`, `下載卸載工具來禁用本地字體。`],
  [`Downloads`, `下載`],
  [`Drafts and teams`, `草稿和團隊`],
  [`Drafts`, `草稿`],
  [`drag`, `拖動`],
  [`Drag`, `拖動`],
  [`Drawing Tools`, `繪畫工具`],
  [`Drop shadow`, `投影`],
  [`Duplicate  to drafts`, `創建副本到草稿`],
  [`Duplicate page`, `創建頁面副本`],
  [`Duplicate selection`, `創建選中項的副本`],
  [`Duplicate to drafts`, `創建副本到草稿`],
  [`Duplicate to your Drafts`, `創建副本到你的草稿`],
  [`Duplicate to your drafts`, `創建副本到你的草稿`],
  [`Duplicate`, `創建副本`],
  [`Duplicating...`, `正在創建副本…`],
  [`Duration`, `持續時間`],
  [`Ease In And Out Back`, `前後回動`],
  [`Ease In And Out`, `前後緩動`],
  [`Ease In Back`, `開始回動`],
  [`Ease In`, `前緩動`],
  [`Ease Out Back`, `結束回動`],
  [`Ease Out`, `後緩動`],
  [`Edit a file`, `編輯一個檔案`],
  [`Edit Current Version`, `編輯當前版本`],
  [`Edit file page`, `編輯檔案頁面`],
  [`Edit object`, `編輯對象`],
  [`Edit shape or image`, `編輯形狀或圖片`],
  [`Edit Style`, `編輯樣式`],
  [`Edit this page`, `編輯這個頁面`],
  [`Edit Version Info`, `編輯版本資訊`],
  [`Edit Version Information`, `編輯版本資訊`],
  [`Edit...`, `編輯…`],
  [`Edit`, `編輯`],
  [`Edited `, `編輯於 `],
  [`Editor Seats`, `編輯者席位`],
  [`editor`, `個編輯者`],
  [`Editors on your team (`, `團隊中的編輯者 (`],
  [`Editors on your team`, `團隊中的編輯者`],
  [`Education team`, `教育版團隊`],
  [`Education Team`, `教育版團隊`],
  [`Education Verification`, `教育版認證`],
  [`Education`, `教育`],
  [`Effect settings`, `效果設定`],
  [`Effect Styles`, `效果樣式`],
  [`Effect`, `效果`],
  [`Effects`, `效果`],
  [`Either this file doesn』t exist or you don』t have permission to view it. Ask the file owner to verify the link and/or update permissions.`, `要麼這個檔案不存在，要麼你沒有權限查看它。請聯系檔案創建者核實連結或更新權限。`],
  [`Ellipse tool`, `橢圓工具`],
  [`Ellipse`, `橢圓`],
  [`Email`, `信箱`],
  [`Enable and set default team libraries for all team files`, `啟用並設定所有團隊檔案的默認團隊元件庫。`],
  [`Enable libraries for all team files from your`, `為所有團隊檔案啟用元件庫，打開`],
  [`Enable libraries`, `啟用元件庫`],
  [`Enable non-Education editors by upgrading to a Professional team.`, `通過升級為專業團隊，以啟用非教育編輯者。`],
  [`Enable quick access to other libraries in this file. `, `可以快速訪問該檔案中的其他元件庫。`],
  [`Enable quick access to other libraries in this file.`, `可以快速訪問該檔案中的其他元件庫。`],
  [`Enable two-factor authentication...`, `啟用兩步驗證…`],
  [`Enable`, `啟用`],
  [`Enabled libraries`, `已啟用的元件庫`],
  [`Enabling a team library will make it show up in all team files.`, `啟用團隊元件庫將使其顯示在所有團隊檔案中。`],
  [`Enter full screen (F)`, `進入全屏模式（F）`],
  [`Enter payment`, `輸入付款方式`],
  [`Enterprise`, `企業`],
  [`Essential keyboard shortcuts`, `必備鍵盤快捷鍵`],
  [`Essential`, `必備`],
  [`Events`, `活動`],
  [`Exclude selection`, `差集所選項`],
  [`Exclusion`, `排除`],
  [`Explore creatotr`, `發現創作者`],
  [`Explore files and plugins made just for Figma`, `探索專門為 Figma 制作的檔案和插件`],
  [`Explore libraries...`, `查看元件庫…`],
  [`Explore the nuances of fonts, type scales, lettering, and type design`, `探索字體、字體比例、字體和字體設計的細微差別`],
  [`Explore, install, use, and remix thousands of files and plugins`, `探索、安裝、使用和演繹成千上萬的檔案和插件`],
  [`Explore`, `探索`],
  [`Export frames to PDF…`, `導出畫框為 PDF…`],
  [`Export overlapping foreground and background layers when disabled`, `禁用時導出重疊的前景和背景圖層。`],
  [`Export settings`, `導出設定`],
  [`Export your designs for use in production or to share with your team.`, `導出你的設計，以便在生產中使用或與你的團隊分享。`],
  [`Export…`, `導出…`],
  [`export`, `導出`],
  [`Export`, `導出`],
  [`Exposure`, `曝光`],
  [`Family`, `字體`],
  [`Favorite`, `收藏`],
  [`Featured Plugins`, `精選插件`],
  [`Features`, `功能`],
  [`Feed`, `動態`],
  [`Feedback and retros`, `反饋和追溯`],
  [`Fig Pick`, `Fig 精選`],
  [`Figma can export to PNG, JPEG, SVG, and PDF.`, `Figma 可以導出 PNG、JPEG、SVG 和 PDF。`],
  [`Figma Catan (Playable)`, `Figma 卡坦島 (可玩)`],
  [`Figma Community`, `Figma 社群`],
  [`Figma helps teams create, test, and ship better designs from start to finish.`, `Figma 在全流程中幫助團隊創建、測試和承載優秀設計。`],
  [`Figma is currently undergoing maintenance and will be temporarily unavailable.`, `Figma 目前正在進行維護，將暫時無法使用。`],
  [`Figma Multiplayer Dice Games!`, `Figma 多人骰子游戲！`],
  [`Figma Organization`, `Figma 組織`],
  [`Figma System`, `Figma 系統`],
  [`Figma will now autosave and apply your offline changes when you』re back online, even if you close your tab.`, `Figma 現在將自動儲存並在你恢復在線時應用你的離線更改，即使你關閉你的標簽頁。`],
  [`File browser`, `檔案瀏覽器`],
  [`File contributions`, `檔案貢獻`],
  [`File deleted forever`, `檔案已永久刪除`],
  [`File deleted`, `檔案已刪除`],
  [`File duplicated to your drafts`, `檔案已創建副本到你的草稿`],
  [`File duplicated to your Drafts`, `檔案已創建副本到你的草稿`],
  [`File duplicated`, `檔案已創建副本`],
  [`File import failed`, `檔案導入失敗`],
  [`File imported successfully`, `檔案導入成功`],
  [`File is temporarily view-only`, `檔案暫時只允許查看`],
  [`File name`, `檔案名`],
  [`File not found`, `找不到檔案`],
  [`File pinned to project`, `檔案已在項目中置頂`],
  [`File restored`, `檔案已恢復`],
  [`File`, `檔案`],
  [`Files with edit access`, `有編輯權限的檔案`],
  [`Files`, `檔案`],
  [`Fill – Scale down or up to fill`, `填充 - 縮小或放大以填充`],
  [`Fill container`, `填充容器`],
  [`Fill`, `填充`],
  [`Final Forms`, `詞尾形式`],
  [`Find and follow Figma creators to get their newest resources`, `尋找並關注 Figma 創作者，獲取他們最新的資源`],
  [`Find next frame`, `查找下一個畫框`],
  [`Find previous frame`, `查找上一個畫框`],
  [`Fine-tune your designs with more layout options`, `用更多的佈局選項微調你的設計`],
  [`Finish setup`, `完成設定`],
  [`Fit – Scale down to fit`, `適應 - 縮小以適應`],
  [`Fit`, `適應`],
  [`Fix position when scrolling`, `滾動時保持固定`],
  [`Fixed Height`, `固定高度`],
  [`Fixed height`, `固定高度`],
  [`Fixed size`, `固定大小`],
  [`Fixed Width`, `固定寬度`],
  [`Fixed width`, `固定寬度`],
  [`Fixed`, `固定`],
  [`Flag as inappropriate...`, `標記濫用…`],
  [`Flatten selection`, `拼合所選項`],
  [`Flatten`, `拼合`],
  [`Flip horizontal`, `水平翻轉`],
  [`Flip objects while resizing`, `調整大小時翻轉對象`],
  [`Flip vertical`, `垂直翻轉`],
  [`Follow`, `關注`],
  [`Follower`, ` 關注者`],
  [`Followers`, ` 關注者`],
  [`followers`, ` 關注者`],
  [`Following`, `正在關注`],
  [`Font default`, `字體默認`],
  [`Font doesn』t support small caps`, `字體不支持小型大寫字母`],
  [`Font doesn』t support subscript`, `字體不支持下標`],
  [`Font doesn』t support superscript`, `字體不支持上標`],
  [`Font`, `字體`],
  [`Fonts`, `字體`],
  [`for all files in your Drafts.`, `給所有草稿裡的檔案。`],
  [`for all team files.`, ` 給所有團隊檔案。`],
  [`for as long as you're a verified Education user`, ` 只要你是驗證過的教育用戶。`],
  [`For individuals`, `個人`],
  [`For scrolling to work on this frame, the content needs to be bigger than the frame.`, `為了讓滾動在這個畫框上可用，內容需要比畫框大。`],
  [`For teams`, `團隊`],
  [`for up to 2 editors and 3 projects`, `最多支持 2 個編輯者和 3 個項目`],
  [`Forced small caps`, `強制小型大寫字母`],
  [`Fraction Denominators`, `分數分母`],
  [`Fraction Numerators`, `分數數字`],
  [`Fractions`, `分數`],
  [`Frame outlines`, `畫框輪廓`],
  [`Frame selection`, `添加畫框`],
  [`Frame tool`, `畫框工具`],
  [`Frame`, `畫框`],
  [`Free for students and educators`, `學生和教育工作者免費`],
  [`Free`, `免費`],
  [`Frequently Used`, `常用`],
  [`Full Widths`, `全寬`],
  [`Fun activities`, `趣味活動`],
  [`Get desktop app`, `下載桌面版應用`],
  [`Get feedback, requests, and copy updates where you』ll use them, not in your inbox.`, `在你使用的時候就獲取反饋、請求和副本更新，而不是在你的收件箱。`],
  [`Get help`, `獲取幫助`],
  [`Get notifications in Slack`, `在 Slack 中接收通知`],
  [`Get started with your team's design system by creating libraries of shared colors, styles, and components. This project already has a set of colors published to your team.`, `通過創建共享的顏色、樣式和元件庫，開始使用你的團隊設計系統。這個項目已經有一套顏色發布給你的團隊。`],
  [`Get Started`, `開始使用`],
  [`Get started`, `開始使用`],
  [`Give feedback, ask a question, or just leave a note of appreciation. Click anywhere in the file to leave a comment.`, `給予反饋，提出問題，或只是留下鼓勵的話。點擊檔案中的任意位置，即可留下評論。`],
  [`Go to frame`, `轉到畫框`],
  [`Go to main component`, `轉到元件母版`],
  [`Gold`, `金色`],
  [`Got it`, `好的`],
  [`Grab a color from elsewhere without losing your flow`, `從任意位置抓取顏色而不中斷工作流`],
  [`Graphic Design`, `視覺設計`],
  [`Grid Styles`, `網格樣式`],
  [`Grid`, `網格`],
  [`Group selection`, `群組所選項`],
  [`Group`, `分組`],
  [`Gutter`, `間距`],
  [`Half Widths`, `半寬`],
  [`Hand tool`, `抓手工具`],
  [`Hard Light`, `強光`],
  [`Height`, `高`],
  [`Help and account`, `幫助和帳戶`],
  [`Help and resources`, `幫助和資源`],
  [`Help center`, `幫助中心`],
  [`Help page`, `幫助頁面`],
  [`Help people discover your file:`, `幫助大家找到你的檔案：`],
  [`Help users easily explore landing pages, carousels, and more. Scroll to selected objects or layers by dragging a connection within the same top-level frame.`, `幫助用戶輕松探索登錄頁面、轉盤等。通過拖動同一頂層畫框內的連接，滾動到選定的對象或圖層。`],
  [`Help`, `幫助`],
  [`Hide canvas UI during changes`, `在更改期間隱藏畫布 UI`],
  [`Hide other layers`, `隱藏其餘圖層`],
  [`Hide Version History`, `隱藏歷史版本`],
  [`Highlight layers on hover`, `突出顯示懸停圖層`],
  [`Highlights`, `標示`],
  [`Historical Forms`, `歷史形式`],
  [`Historical Ligatures`, `歷史連字`],
  [`Hold up...`, `稍等一下…`],
  [`Horizontal and vertical scrolling`, `水平 & 垂直滾動`],
  [`Horizontal direction`, `水平方向`],
  [`Horizontal Padding`, `水平間距`],
  [`Horizontal scrolling`, `水平滾動`],
  [`Horizontal spacing`, `水平間距`],
  [`Horizontal`, `水平`],
  [`Hover`, `懸停`],
  [`Hue`, `色相`],
  [`Hug contents`, `適應內容`],
  [`Icons`, `圖標`],
  [`If you are an admin of a Starter Team, you can upgrade it to an Education Team. Just choose the "Education Plan」 when upgrading your team.`, `如果你是入門版團隊的管理員，你可以將其升級為教育團隊。只要在升級團隊時選擇 "教育計劃 "即可。`],
  [`Ignore constraints (frames only)`, `忽略約束（僅畫框）`],
  [`Illustrations`, `插畫`],
  [`Image Resized`, `圖片已縮放`],
  [`Image`, `圖片`],
  [`Import canceled.`, `已取消導入。`],
  [`Import files`, `導入檔案`],
  [`Import Sketch files`, `導入 Sketch 檔案`],
  [`Import`, `導入`],
  [`Importing file...`, `正在導入檔案…`],
  [`In Development`, `正在開發`],
  [`Inactive`, `不更動`],
  [`Increase font size`, `增大字號`],
  [`Increase font weight`, `增大字重`],
  [`Increase letter spacing`, `增大字距`],
  [`Increase line height`, `增大行高`],
  [`Independent corners`, `獨立圓角`],
  [`Individual padding for more precise layouts`, `獨立的邊距使佈局更精確`],
  [`Initial Forms`, `詞首形式`],
  [`Inner border`, `內邊框`],
  [`Inner shadow`, `內陰影`],
  [`Inside`, `內部`],
  [`inspect`, `檢查`],
  [`Install Font Helper`, `安裝字體幫助程式`],
  [`Install`, `安裝`],
  [`Installed`, `已安裝`],
  [`Installs`, `安裝`],
  [`Instance options`, `元件實例選項`],
  [`Instance`, `元件實例`],
  [`Instant`, `即時`],
  [`Integrations`, `集成`],
  [`Interaction details`, `互動細節`],
  [`Interaction`, `互動`],
  [`Interactions`, `互動`],
  [`Intersect selection`, `交集所選項`],
  [`Invert zoom direction`, `反轉縮放方向`],
  [`Invite email sent again!`, `邀請郵件已再次發送`],
  [`Invite members`, `邀請成員`],
  [`Invite someone…`, `邀請某人…`],
  [`Invite team members`, `邀請團隊成員`],
  [`Invite-only — let me choose who has access`, `僅限邀請 - 讓我選擇誰可以訪問`],
  [`Invite-only`, `僅限邀請`],
  [`Invite`, `邀請`],
  [`Isolated Forms`, `獨立形式`],
  [`Italic`, `斜體`],
  [`Join beta`, `加入測試版`],
  [`Join selection`, `連接所選項`],
  [`Join`, `節點`],
  [`Just drag your Sketch files onto the browser and we』ll convert them to Figma for you.`, `只需將你的 Sketch 檔案拖到瀏覽器上，我們將為你轉換為 Figma 檔案。`],
  [`Keep tool selected after use`, `使用後保持工具選擇`],
  [`Kerning Pairs`, `字偶距組合`],
  [`Kerning`, `字偶距`],
  [`Key/gamepad`, `鍵盤/游戲手把`],
  [`Key`, `按鍵`],
  [`Keyboard shortcuts`, `鍵盤快捷鍵`],
  [`Keyboard zooms into selection`, `鍵盤縮放所選項`],
  [`Landscape`, `橫屏`],
  [`Last active: All`, `最近更動：全部`],
  [`Last active: More than 3 months ago`, `最近更動：超過 3 個月前`],
  [`Last active: More than 30 days ago`, `最近更動：超過 30 天前`],
  [`Last active: More than 7 days ago`, `最近更動：超過 7 天前`],
  [`Last active`, `最近更新`],
  [`Last activity`, `最近更新`],
  [`Last modified`, `最後修改`],
  [`last month`, `上個月`],
  [`Last updated `, `最近更新：`],
  [`Last updated`, `最近更新`],
  [`Last viewed`, `最近瀏覽`],
  [`last year`, `去年`],
  [`Later`, `稍後`],
  [`Layer blur`, `圖層模糊`],
  [`Layer`, `圖層`],
  [`Layers Panel`, `圖層面板`],
  [`Layers`, `圖層`],
  [`Layout grid`, `佈局網格`],
  [`Layout grids hidden`, `隱藏佈局網格`],
  [`Layout grids visible`, `顯示佈局網格`],
  [`Layout grids`, `佈局網格`],
  [`Learn more about team plans`, `了解更多關於團隊計劃的資訊`],
  [`Learn more…`, `了解更多…`],
  [`Learn more...`, `了解更多…`],
  [`Learn more`, `了解更多`],
  [`Leave notes right in your design files.`, `在你的設計檔案中直接留下資訊。`],
  [`Leave team`, `離開團隊`],
  [`Leave`, `離開`],
  [`leave`, `離開`],
  [`Left & Right`, `左 & 右`],
  [`Left and right`, `左右拉伸`],
  [`Left padding`, `左邊距`],
  [`Left`, `左`],
  [`Legal summary`, `法律摘要`],
  [`Letter case`, `字母大小寫`],
  [`Letter spacing`, `字距`],
  [`Letterforms`, `字母形式`],
  [`Libraries`, `元件庫`],
  [`Library`, `元件庫`],
  [`License`, `授權`],
  [`Licensed under `, `授權協議：`],
  [`Ligatures`, `連字`],
  [`Lighten`, `變亮`],
  [`Liked plugin!`, `已點贊插件！`],
  [`Likes`, `點贊`],
  [`Line Arrow`, `線性箭頭`],
  [`Line height`, `行高`],
  [`Line tool`, `直線工具`],
  [`Line`, `直線`],
  [`Linear`, `線性漸變`],
  [`Link copied to clipboard`, `連結已複製到剪貼板`],
  [`Link deleted`, `連結已刪除`],
  [`Link to selected frame`, `連結到已選中的畫框`],
  [`Live device preview`, `實時設備預覽`],
  [`Local colors`, `本地顏色`],
  [`Local components`, `本地元件`],
  [`Local fonts are currently not enabled.`, `本地字體目前尚未啟用。`],
  [`Local styles`, `本地樣式`],
  [`Lock/Unlock selection`, `鎖定/解鎖所選項`],
  [`Lock/Unlock`, `鎖定/解鎖`],
  [`Log in`, `登錄`],
  [`Log Out`, `退出`],
  [`Log out`, `退出`],
  [`Lower case`, `小寫`],
  [`Lowercase`, `小寫`],
  [`Luminosity`, `明度`],
  [`Main component`, `元件母版`],
  [`Manage plugins…`, `管理插件…`],
  [`Manage Slack notifications`, `管理 Slack 通知`],
  [`Manual`, `手動`],
  [`Margin`, `邊距`],
  [`Mark all as read`, `全部標記為已讀`],
  [`Mask outlines hidden`, `隱藏遮罩輪廓`],
  [`Mask outlines visible`, `顯示遮罩輪廓`],
  [`Mask outlines`, `遮罩輪廓`],
  [`Mask`, `遮罩`],
  [`Math`, `數學`],
  [`Mathematical Greek`, `數學希臘字符`],
  [`Measure to selection`, `測量到所選項的距離`],
  [`Medial Forms`, `詞中形式`],
  [`Meeting notes`, `會議記錄`],
  [`Members`, `成員`],
  [`Midnight Green`, `午夜綠`],
  [`Mirror angle and length`, `角度與長度對稱`],
  [`Mirror angle`, `角度對稱`],
  [`Missing Font`, `丟失的字體`],
  [`Missing Fonts`, `丟失的字體`],
  [`Miter Angle`, `斜度`],
  [`Mixed`, `多個值`],
  [`Mobile Design`, `移動端設計`],
  [`Mobile design`, `移動端設計`],
  [`Model`, `型號`],
  [`Monospace lowercase/old-style`, `等寬小寫字母/不等高`],
  [`Monospace uppercase/lining`, `等寬大寫字母/等高`],
  [`Monthly Plan`, `月付計劃`],
  [`More features`, `更多功能`],
  [`More Options`, `更多選項`],
  [`More than 3 months ago`, `超過 3 個月前`],
  [`More than 30 days ago`, `超過 30 天前`],
  [`More than 7 days ago`, `超過 7 天前`],
  [`more...`, `更多…`],
  [`More`, `更多`],
  [`Mouse down`, `按下鼠標時`],
  [`Mouse enter`, `鼠標進入`],
  [`Mouse leave`, `鼠標離開`],
  [`Mouse up`, `釋放鼠標時`],
  [`Move Down`, `下移`],
  [`Move in`, `移入`],
  [`Move Left`, `左移`],
  [`Move out`, `移出`],
  [`Move project`, `移動項目`],
  [`Move Right`, `右移`],
  [`Move this file to a Professional team in order to publish components to that team's library.`, `將此檔案移動到專業團隊，以便將元件發布到該團隊的庫中。`],
  [`Move to page`, `移到頁面`],
  [`Move to project…`, `移動到項目…`],
  [`Move to project...`, `移動到項目…`],
  [`Move to project`, `移動到項目`],
  [`Move to team to publish components`, `移動到團隊來發布元件`],
  [`Move to team...`, `移動到團隊…`],
  [`Move to team`, `移動到團隊`],
  [`Move Tool`, `移動工具`],
  [`Move tool`, `移動工具`],
  [`Move Tools`, `移動工具`],
  [`Move Up`, `上移`],
  [`Move while resizing`, `調整大小時移動`],
  [`Move`, `移動`],
  [`Multiplayer cursors hidden`, `隱藏多人鼠標指針`],
  [`Multiplayer cursors visible`, `顯示多人鼠標指針`],
  [`Multiplayer cursors`, `多人鼠標指針`],
  [`Multiplayer`, `多用戶`],
  [`Multiply`, `正片疊底`],
  [`Name this version`, `給這個版本命名`],
  [`Name your team`, `給團隊取個名字`],
  [`Name`, `名字`],
  [`Navigate to`, `導航到`],
  [`New file`, `新建檔案`],
  [`New from Sketch file…`, `從 Sketch 檔案新建…`],
  [`New Page`, `新建頁面`],
  [`New Plugin...`, `新建插件…`],
  [`New project`, `新建項目`],
  [`New Team…`, `新建團隊…`],
  [`New Team...`, `新建團隊…`],
  [`New`, `新建`],
  [`Next page`, `下一頁`],
  [`Next to review`, `下一步並檢查`],
  [`Next`, `下一個`],
  [`No `, `沒有`],
  [`No files yet`, `還沒有檔案`],
  [`No members to show.`, `沒有可顯示的成員。`],
  [`No mirroring`, `不對稱`],
  [`No results found`, `沒有找到結果`],
  [`No scrolling`, `無滾動`],
  [`No selected layers have export settings. Click + in the export section of the properties panel to add one.`, `選中的圖層都沒有設定導出。在屬性面板的導出部分點擊 + 來添加一個。`],
  [`No syncing, no waiting, no merge conflicts.`, `無需同步、無需等待、無需合並衝突。`],
  [`No team permissions`, `沒有團隊權限`],
  [`No updates available`, `無可用更新`],
  [`None`, `無`],
  [`Normal`, `正常`],
  [`Not applicable for selected text`, `不適用於選定的文本`],
  [`Nothing liked yet`, `沒有點贊任何內容`],
  [`Nothing published yet`, `沒有發布任何內容`],
  [`Notifications`, `通知`],
  [`Now, they』re both simpler and more powerful – paths finally work the way they should.`, `現在，它們既簡單又強大，路徑最終將按該有的方式工作。`],
  [`Nudge amount…`, `單位微調…`],
  [`Nudge amount`, `單位微調`],
  [`Number `, `數字`],
  [`Numbers`, `數字`],
  [`Object`, `對象`],
  [`Objects can now be set to fill container, hug contents, and fixed on both axes. `, `對象現在可以設定為填充容器，緊貼內容，並固定在兩個軸上。`],
  [`Offline changes will be synced with Figma when you go online.`, `離線更改將在你上線時與 Figma 同步。`],
  [`Offset`, `偏置`],
  [`OK`, `好的`],
  [`On click`, `單擊`],
  [`On drag`, `拖動`],
  [`On tap`, `輕觸`],
  [`One of the coolest things about Figma is that you don』t have to start from scratch to get to work.`, `Figma 最酷的一點是，你不必從頭開始工作。`],
  [`Only members of Professional Teams can publish components to a shared library. Create a new team or join an existing team to use this feature.`, `只有專業團隊的成員才能將元件發布到共享庫中。創建一個新的團隊或加入一個現有的團隊來使用此功能。`],
  [`Only people invited to this file`, `只有被邀請的人`],
  [`Only team admins can enable libraries for the team.`, `只有團隊管理員才能為團隊啟用元件庫。`],
  [`Only yours `, `僅我的`],
  [`Only yours`, `僅我的`],
  [`Opacity`, `不透明度`],
  [`Open a file to learn more about Figma』s powerful editing features!`, `打開一個檔案，了解更多關於 Figma 強大的編輯功能！`],
  [`Open admin dashboard`, `打開管理員儀表盤`],
  [`Open assets panel`, `打開資源面板`],
  [`Open code panel`, `打開程式碼面板`],
  [`Open console`, `打開控制台`],
  [`Open design panel`, `打開設計面板`],
  [`Open files in the Desktop App from now on?`, `從現在開始都在桌面應用中打開檔案嗎？`],
  [`Open font settings`, `打開字體設定`],
  [`Open in App`, `應用中打開`],
  [`Open in desktop app`, `在桌面應用中打開`],
  [`Open in Editor`, `在編輯器中打開`],
  [`Open in new tab`, `在新標簽頁中打開`],
  [`Open layers panel`, `打開圖層面板`],
  [`Open link`, `打開連結`],
  [`Open links in desktop app`, `在桌面應用打開連結`],
  [`Open original file`, `打開原始檔案`],
  [`Open overlay`, `打開疊加`],
  [`Open playground`, `打開游樂場`],
  [`Open prototype panel`, `打開原型面板`],
  [`Open the playground`, `打開游樂場`],
  [`Open to sync`, `打開並同步`],
  [`Open View Only`, `僅查看模式打開`],
  [`Open`, `打開`],
  [`Options`, `選項`],
  [`or`, `或者`],
  [`Order`, `順序`],
  [`Ordinals`, `序數字`],
  [`Organization`, `組織版`],
  [`Organize your design system with Variants so even the most complex components are structured intuitively. Combine variations of the same component and simplify your asset library.`, `使用變體組織你的設計系統，因此即使是最復雜的元件也能直觀地組織起來。結合同一元件的變體，簡化你的資產庫。`],
  [`Original case`, `初始大小寫`],
  [`Other options`, `其他選項`],
  [`Others`, `其他人`],
  [`Outer Border`, `外邊框`],
  [`Outline stroke`, `輪廓化描邊`],
  [`Outline Text`, `輪廓化文本`],
  [`Outlines hidden`, `隱藏輪廓`],
  [`Outlines visible`, `顯示輪廓`],
  [`Outlines`, `輪廓`],
  [`Outside`, `外部`],
  [`Overflow behavior`, `溢出行為`],
  [`Overlay`, `疊加`],
  [`Owner`, `創建者`],
  [`owner`, `創建者`],
  [`Pack horizontal`, `水平堆疊`],
  [`Pack vertical`, `垂直堆疊`],
  [`Packed`, `堆疊`],
  [`Padding around items`, `內邊距`],
  [`Page deleted`, `頁面已刪除`],
  [`Page duplicated`, `已創建頁面副本`],
  [`Pages`, `頁面`],
  [`Paint bucket`, `顏料桶`],
  [`Pan`, `抓手`],
  [`Panels`, `面板`],
  [`Paper`, `紙張`],
  [`Paragraph indent`, `段落縮進`],
  [`Paragraph spacing`, `段落間距`],
  [`Parent component`, `父級元件`],
  [`Pass Through`, `穿透`],
  [`Password`, `密碼`],
  [`Paste and match style`, `粘貼並匹配樣式`],
  [`Paste over selection`, `粘貼至所選位置`],
  [`Paste properties`, `粘貼屬性`],
  [`Paste to replace`, `粘貼替換`],
  [`Paste`, `粘貼`],
  [`Pasting...`, `正在粘貼…`],
  [`Pen tool`, `鋼筆工具`],
  [`Pen tools have always been scary to use because they can be touchy and fragile.`, `一直以來，鋼筆工具都是讓人害怕的，因為它們既敏感又脆弱。`],
  [`Pen`, `鋼筆`],
  [`Pencil tool`, `鉛筆工具`],
  [`Pencil`, `鉛筆`],
  [`People who have edited this project will appear here.`, `編輯過這個項目的人將出現在這裡。`],
  [`People`, `人員`],
  [`per editor when billed annually`, `每個編輯者（年付）`],
  [`per editor, annual billing only`, `每個編輯者（僅限年付）`],
  [`Permanently delete this team and all resources within`, `永久性地刪除這個團隊和其中的所有資源`],
  [`Permissions`, `授權`],
  [`Personal access tokens allow you to access your own data via the API. Do not give out your personal access tokens to anybody who you don't want to access your files.`, `個人訪問令牌允許你通過API訪問你自己的數據。請不要將你的個人訪問令牌提供給任何你不想訪問你的檔案的人。`],
  [`Personal access tokens`, `個人訪問令牌`],
  [`Phone`, `手機`],
  [`Pick color`, `吸取顏色`],
  [`Pin to project`, `在項目中置頂`],
  [`Pinned`, `置頂`],
  [`Pixel grid hidden`, `隱藏像素網格`],
  [`Pixel grid visible`, `顯示像素網格`],
  [`Pixel grid`, `像素網格`],
  [`Pixel preview disabled`, `像素預覽已禁用`],
  [`Pixel preview enabled (1x)`, `像素預覽已啟用 (1x)`],
  [`Pixel preview enabled (2x)`, `像素預覽已啟用 (2x)`],
  [`Pixel preview`, `像素預覽`],
  [`Place image…`, `放置圖片…`],
  [`Plan and billing`, `計劃和計費`],
  [`Planning and Retros`, `規劃和回溯`],
  [`Please confirm your email address`, `請確認你的郵件地址`],
  [`Plugin / file cover`, `插件 / 檔案封面`],
  [`Plugin administration`, `插件管理`],
  [`Plugin icon`, `插件圖標`],
  [`Plugin Installed`, `插件安裝完成`],
  [`Plugin`, `插件`],
  [`Plugins`, `插件`],
  [`Polygon`, `多邊形`],
  [`Popular`, `流行`],
  [`Portrait`, `豎屏`],
  [`Position`, `位置`],
  [`Post`, `確定`],
  [`Preferences`, `偏好設定`],
  [`Present`, `演示`],
  [`Presentation`, `演示`],
  [`Preserve scroll position`, `滾動時固定位置`],
  [`Presets`, `預設`],
  [`Press it now to quickly hide the panes and focus on your work`, `現在按下它可以快速隱藏面板，專注於你的工作`],
  [`Press`, `按下`],
  [`Preview as a`, `預覽形式`],
  [`Preview`, `預覽`],
  [`Previous page`, `上一頁`],
  [`Pricing FAQ`, `價格常見問題`],
  [`Pricing`, `定價`],
  [`Privacy`, `隱私`],
  [`Professional`, `專業版`],
  [`Profile banner`, `個人主頁橫幅`],
  [`Project name`, `項目名稱`],
  [`Project`, `項目`],
  [`Projects contain your design files. Let』s create your first project now.`, `項目包含你的設計檔案。現在讓我們來創建你的第一個項目。`],
  [`Projects with edit access`, `有編輯權限的項目`],
  [`Projects`, `項目`],
  [`Properties`, `屬性`],
  [`Proportional Alternate Widths`, `比例替代寬度`],
  [`Proportional lowercase/old-style`, `比例小寫字母/不等高`],
  [`Proportional uppercase/lining`, `比例大寫字母/等高`],
  [`Proportional Widths`, `變寬`],
  [`Prototype`, `原型`],
  [`prototype`, `原型`],
  [`Prototyping Features`, `原型設計能力`],
  [`Prototyping`, `原型設計`],
  [`Public profile`, `公開個人主頁`],
  [`Public`, `公開`],
  [`Publish a version of this file to the Community for the public to duplicate and remix.`, `向社群發布該檔案的一個版本，供大家複製和重新演繹。`],
  [`Publish file`, `發布檔案`],
  [`Publish library`, `發布元件庫`],
  [`Publish styles & components`, `發布樣式和元件`],
  [`Publish styles and components`, `發布樣式和元件`],
  [`Publish styles only`, `僅發布樣式`],
  [`Publish styles`, `發布樣式`],
  [`Publish to Community`, `發布到社群`],
  [`Publish update...`, `發布更新…`],
  [`Publish your changes to your team library.`, `將你的更改發布到你的團隊元件庫中。`],
  [`Publish...`, `發布…`],
  [`Publish`, `發布`],
  [`Published and up to Date`, `已發布且為最新`],
  [`Published and up to date`, `已發布且為最新`],
  [`Published`, `已發布時間`],
  [`Publisher`, `發布者`],
  [`Publishing libraty`, `正在發布元件庫`],
  [`Push overrides to main component`, `覆蓋元件母版`],
  [`Push`, `推動`],
  [`Radial`, `徑向漸變`],
  [`Radius`, `圓角`],
  [`Randomize`, `隨機化`],
  [`Rare Ligatures`, `罕見連字`],
  [`Rasterize selection`, `像素化所選項`],
  [`Read more`, `閱讀全文`],
  [`Ready to upgrade your plan?`, `準備升級你的計劃？`],
  [`Recent contributors`, `最近貢獻者`],
  [`Recent projects`, `近期項目`],
  [`Recent`, `最近`],
  [`Recently viewed`, `最近瀏覽`],
  [`Rectangle tool`, `矩形工具`],
  [`Rectangle`, `矩形`],
  [`Redo`, `重做`],
  [`Region Tools`, `區域工具`],
  [`Related components`, `相關元件`],
  [`Related tags`, `相關標簽`],
  [`Release notes`, `版本說明`],
  [`Releases`, `版本`],
  [`Relevance`, `相關`],
  [`Remote Design Sprinting (RDS)`, `遠程設計沖刺（RDS）`],
  [`Remote Design`, `遠程設計`],
  [`Remove all connections`, `移除全部連接`],
  [`Remove auto layout`, `移除自動佈局`],
  [`Remove connections`, `移除連接`],
  [`Remove fill`, `移除填充`],
  [`Remove from favorites`, `從收藏夾中移除`],
  [`Remove from library`, `從元件庫移除`],
  [`Remove from pinned`, `從置頂中移除`],
  [`Remove from recent`, `從最近中移除`],
  [`Remove mask`, `移除遮罩`],
  [`Remove property`, `移除屬性`],
  [`Remove stroke`, `移除描邊`],
  [`remove team access`, `移除團隊訪問權限`],
  [`Remove...`, `移除…`],
  [`Remove`, `移除`],
  [`remove`, `移除`],
  [`Removing a connection`, `刪除連接`],
  [`Rename duplicated layers`, `重命名已創建的副本圖層`],
  [`Rename page`, `重命名頁面`],
  [`Rename selection`, `重命名所選項`],
  [`Rename team`, `重命名團隊`],
  [`Rename`, `重命名`],
  [`Replace Fonts`, `替換字體`],
  [`Replacement`, `替換字體`],
  [`Reply`, `回復`],
  [`Resend Email`, `重新發送郵件`],
  [`Resend invite`, `重新發送邀請`],
  [`resend`, `重新發送`],
  [`Reset all overrides`, `重置所有覆蓋`],
  [`Reset effects`, `重置效果`],
  [`Reset exports`, `重置導出`],
  [`Reset fill`, `重置填充`],
  [`Reset filters`, `重置過濾器`],
  [`Reset instance`, `重置元件實例`],
  [`Reset name`, `重置名稱`],
  [`Reset onboarding`, `重置新手引導`],
  [`Reset others`, `重置其他`],
  [`Reset overlay`, `重置疊加`],
  [`Reset overrides`, `重置覆蓋`],
  [`Reset size`, `重置大小`],
  [`Reset stroke`, `重置描邊`],
  [`Reset text style`, `重置文本樣式`],
  [`Reset text`, `重置文本`],
  [`Reset transition`, `重置過渡`],
  [`Reset visibility`, `重置可見性`],
  [`Resize from center`, `從中心調整大小`],
  [`Resize Proportionally`, `按比例調整大小`],
  [`Resize proportionally`, `按比例調整大小`],
  [`Resize to Fit`, `適應大小`],
  [`Resizing`, `調整大小`],
  [`Resolve`, `解決`],
  [`Resource use`, `資源使用情況`],
  [`Resources`, `資源`],
  [`Restart (R)`, `重新開始（R）`],
  [`Restore component`, `恢復元件母版`],
  [`Restore Component`, `恢復元件母版`],
  [`Restore default thumbnail`, `恢復默認封面`],
  [`Restore main component`, `恢復元件母版`],
  [`Restore this version`, `還原到這個版本`],
  [`Restore`, `恢復`],
  [`Restored main component`, `已恢復元件母版`],
  [`Return to instance`, `返回實例`],
  [`Review our `, `查看我們的`],
  [`Review team`, `確認團隊`],
  [`Review`, `查看`],
  [`Revoke access`, `撤銷訪問`],
  [`Right padding`, `右邊距`],
  [`right-click`, `右擊`],
  [`Right-to-left Mirrored Forms`, `從右到左鏡像形式`],
  [`Right`, `右側`],
  [`Rotate 180˚`, `旋轉 180°`],
  [`Rotate 90˚ left`, `向左旋轉 90°`],
  [`Rotate 90˚ right`, `向右旋轉 90°`],
  [`Rotation`, `旋轉`],
  [`Round to pixel`, `對齊像素`],
  [`Round`, `圓頭`],
  [`Rows`, `行`],
  [`Ruby Notation Forms`, `注音字符形式`],
  [`Rulers`, `標尺`],
  [`Run last plugin`, `運行最後一個插件`],
  [`Running your prototype`, `啟動你的原型`],
  [`Saturation`, `飽和度`],
  [`Save 20%`, `節省 20%`],
  [`Save as .fig…`, `另存為 .fig 檔案…`],
  [`Save local copy…`, `儲存本地副本…`],
  [`Save time and accelerate your workflow with beautifully designed templates`, `使用設計精美的模板節省時間，加快工作流程`],
  [`Save to version history…`, `儲存至歷史版本…`],
  [`Save`, `儲存`],
  [`Saving…`, `儲存中…`],
  [`Scale`, `縮放`],
  [`Scientific Inferiors`, `科學下標符號`],
  [`Screen`, `濾色`],
  [`Scroll to`, `滾動到`],
  [`Search the Figma Community`, `搜索 Figma 社群`],
  [`Search through all of Figma』s commands`, `搜索 Figma 的全部命令`],
  [`Search…`, `搜索…`],
  [`Search`, `搜索`],
  [`seat/month`, `席位/月`],
  [`Security`, `安全`],
  [`See all`, `查看全部`],
  [`See edit access`, `查看編輯訪問`],
  [`See edit permissions`, `查看編輯權限`],
  [`See how it works`, `看看 Figma 如何工作`],
  [`See what's being created in Figma`, `看看 Figma 裡面正在創建什麼`],
  [`Select a frame or object in a frame and use the circular node to drag a connection to another frame.`, `選擇一個畫框或一個畫框中的對象，然後使用圓形節點將連接拖動到另一個畫框。`],
  [`Select all with same effect`, `選擇全部相同效果`],
  [`Select all with same fill`, `選擇全部相同填充顏色`],
  [`Select all with same font`, `選擇全部相同字體`],
  [`Select all with same instance`, `選擇全部相同元件實例`],
  [`Select all with same properties`, `選擇全部相同屬性`],
  [`Select all with same stroke`, `選擇全部相同描邊`],
  [`Select all with same text properties`, `選擇全部相同文本屬性`],
  [`Select all`, `全選`],
  [`Select child`, `選擇子元素`],
  [`Select Component`, `選擇元件`],
  [`Select conflicting variants`, `選擇衝突的變體`],
  [`Select corrupted variants`, `選擇損壞的變體`],
  [`Select inverse`, `反選`],
  [`Select layer menu`, `選擇圖層菜單`],
  [`Select layer`, `選擇圖層`],
  [`Select next sibling`, `選擇下一個同級元素`],
  [`Select none`, `取消選擇`],
  [`Select parents`, `選擇父元素`],
  [`Select previous sibling`, `選擇上一個同級元素`],
  [`Select the frame your prototype will begin with.`, `選擇你原型起始的畫框。`],
  [`Select which comment threads on this file you'll receive emails and notifications for.`, `選擇這個檔案中的哪些評論主題，你將收到電子郵件和通知。`],
  [`Selection colors`, `選擇的顏色`],
  [`Selection`, `選擇`],
  [`Send backward`, `下移一層`],
  [`Send Invite `, `發送邀請 `],
  [`Send invite`, `發送邀請`],
  [`Send to back`, `移到底層`],
  [`Set as thumbnail`, `設為封面`],
  [`Set default properties`, `設定默認屬性`],
  [`Set opacity to 10%`, `設定不透明度為 10%`],
  [`Set opacity to 100%`, `設定不透明度為 100%`],
  [`Set opacity to 50%`, `設定不透明度為 50%`],
  [`Set profile handle`, `設定個人主頁帳號`],
  [`Set team profile handle`, `設定團隊主頁帳號`],
  [`Setting precise constraints lets you build fluid layouts to support multiple device sizes and breakpoints within the same group.`, `設定精確的約束條件可以讓你構建流式佈局，以支持同一組內的多種設備尺寸和斷點。`],
  [`Settings`, `設定`],
  [`Shadow spread is not supported for vector type`, `向量圖層不支持陰影擴展`],
  [`Shadows`, `陰影`],
  [`Shape Tools`, `形狀工具`],
  [`Shape`, `形狀`],
  [`Share `, `分享 `],
  [`Share components and styles across your team by publishing them to the team library.`, `通過將元件和樣式發布到團隊元件庫中，可以在你的團隊中共享它們。`],
  [`Share components and styles across your team by publishing them to the Team Library.`, `通過將元件和樣式發布到團隊元件庫中，在你的團隊中共享它們。`],
  [`Share on Facebook`, `分享到 Facebook`],
  [`Share on Twitter`, `分享到 Twitter`],
  [`Share prototype`, `分享原型`],
  [`Share your projects with teammates, clients, and stakeholders but don』t let them mess up your files.`, `與隊友、客戶和利益相關者分享你的項目，但不要讓他們弄亂你的檔案。`],
  [`Share`, `分享`],
  [`Shared Projects`, `共享的項目`],
  [`Shared`, `已共享`],
  [`Sharing and Permissions`, `分享和權限`],
  [`Show as grid`, `顯示為網格`],
  [`Show as list`, `顯示為列表`],
  [`Show assets`, `顯示資源`],
  [`Show autosave versions`, `顯示自動儲存的版本`],
  [`Show dimensions on objects`, `在對象上顯示尺寸`],
  [`Show Full Version History`, `顯示完整版本歷史`],
  [`Show Google Fonts`, `顯示谷歌字體`],
  [`Show Hotspot Hints on Click`, `點擊時顯示熱區提示`],
  [`Show in exports`, `在導出中顯示`],
  [`Show in Files`, `在檔案中顯示`],
  [`Show in project`, `在項目中顯示`],
  [`Show left sidebar`, `顯示左側邊欄`],
  [`Show less`, `收起內容`],
  [`Show me what』s new`, `查看新功能`],
  [`Show me`, `定位`],
  [`Show notifications`, `顯示通知`],
  [`Show Only Your Comments`, `只顯示你的評論`],
  [`Show prototype settings`, `顯示原型設定`],
  [`Show resolved comments`, `顯示已解決的評論`],
  [`Show Resolved Comments`, `顯示已解決的評論`],
  [`Show selection colors`, `顯示所選項的顏色`],
  [`Show slices`, `顯示切片`],
  [`Show this next time`, `下次繼續顯示`],
  [`Show Toolbar and Footer`, `顯示工具條和頁腳`],
  [`Show version history`, `查看版本歷史`],
  [`Show/Hide selection`, `顯示/隱藏所選項`],
  [`Show/Hide UI`, `顯示/隱藏界面`],
  [`Show/Hide`, `顯示/隱藏`],
  [`Show`, `顯示`],
  [`Silver`, `銀色`],
  [`Simple Kanban Template`, `簡易看板模板`],
  [`Size`, `尺寸`],
  [`Skip for now`, `暫時跳過`],
  [`Slashed Zero`, `斜槓零`],
  [`Slice tool`, `切片工具`],
  [`Slice`, `切片`],
  [`Slide in`, `滑入`],
  [`Slide out`, `滑出`],
  [`Small caps`, `小型大寫字母`],
  [`Small nudge`, `小微調`],
  [`Smart animate matching layers`, `智慧動畫匹配圖層`],
  [`Smart animate`, `智慧動畫`],
  [`Smooth join selection`, `平滑連接所選項`],
  [`Snap to geometry`, `對齊到形狀`],
  [`Snap to objects`, `對齊到對象`],
  [`Snap to pixel grid disabled`, `已禁用對齊到像素`],
  [`Snap to pixel grid enabled`, `已啟用對齊到像素`],
  [`Snap to pixel grid`, `對齊到像素`],
  [`Social media`, `社群媒體`],
  [`Soft Light`, `柔光`],
  [`Solid`, `純色`],
  [`Some variants are missing properties.`, `有些變體缺少屬性。`],
  [`Some variants have the same property values applied. Change the values of these to resolve this.`, `有些變體應用了相同的屬性值。修改這些變體的值來解決這個問題。`],
  [`Sort by`, `排序方式`],
  [`Space between`, `等距`],
  [`Space Grey`, `深空灰`],
  [`Space`, `空格`],
  [`Spacing between items`, `項目間距`],
  [`Spread`, `擴展`],
  [`Square`, `方頭`],
  [`Standard Ligatures`, `標准連字`],
  [`Star`, `星形`],
  [`Start ascending from`, `起始編號`],
  [`Start sequence from`, `起始編號`],
  [`Starter team`, `入門版團隊`],
  [`Starter`, `入門版`],
  [`Starting frame`, `起始畫框`],
  [`Status`, `狀態`],
  [`Stretch Left and Right`, `左右拉伸`],
  [`Stretch Top and Bottom`, `上下拉伸`],
  [`Stretch`, `拉伸`],
  [`Strikethrough`, `刪除線`],
  [`Stroke`, `描邊`],
  [`Students and Educators`, `學生和教育工作者`],
  [`Style`, `樣式`],
  [`Styles and Components`, `樣式和元件`],
  [`Stylistic Alternates`, `字體替代字形`],
  [`Stylistic Set 1`, `字體組合 1`],
  [`Stylistic Set 10`, `字體組合 10`],
  [`Stylistic Set 11`, `字體組合 11`],
  [`Stylistic Set 12`, `字體組合 12`],
  [`Stylistic Set 13`, `字體組合 13`],
  [`Stylistic Set 14`, `字體組合 14`],
  [`Stylistic Set 15`, `字體組合 15`],
  [`Stylistic Set 16`, `字體組合 16`],
  [`Stylistic Set 17`, `字體組合 17`],
  [`Stylistic Set 18`, `字體組合 18`],
  [`Stylistic Set 19`, `字體組合 19`],
  [`Stylistic Set 2`, `字體組合 2`],
  [`Stylistic Set 20`, `字體組合 20`],
  [`Stylistic Set 3`, `字體組合 3`],
  [`Stylistic Set 4`, `字體組合 4`],
  [`Stylistic Set 5`, `字體組合 5`],
  [`Stylistic Set 6`, `字體組合 6`],
  [`Stylistic Set 7`, `字體組合 7`],
  [`Stylistic Set 8`, `字體組合 8`],
  [`Stylistic Set 9`, `字體組合 9`],
  [`Stylistic sets 1`, `字體組合 1`],
  [`Stylistic sets`, `字體組合`],
  [`Subscript`, `下標`],
  [`Subscription`, `訂閱`],
  [`Substitute smart quotes`, `智慧引號替換`],
  [`Subtract selection`, `減去頂層所選項`],
  [`Successfully published library updates`, `元件庫更新發布成功`],
  [`Suffix`, `後綴`],
  [`Superscript`, `上標`],
  [`Support:`, `技術支持：`],
  [`Support`, `支持`],
  [`Swap component instance`, `交換元件實例`],
  [`Swap fill and stroke`, `交換填充和描邊`],
  [`Swap Instance`, `交換實例`],
  [`Swap instance`, `交換實例`],
  [`Swap with`, `交換到`],
  [`Table`, `表格`],
  [`Tablet`, `平板電腦`],
  [`Tags`, `標簽`],
  [`Team building`, `團隊建設`],
  [`Team libraries`, `團隊元件庫`],
  [`Team library is a Professional plan-only feature`, `團隊元件庫是專業版計劃才有的功能`],
  [`Team library`, `團隊元件庫`],
  [`Team name`, `團隊名稱`],
  [`Team profile handle`, `團隊主頁帳號`],
  [`Team Retrospective Template`, `團隊回顧模板`],
  [`team settings`, `團隊設定`],
  [`Team Templates`, `團隊模板`],
  [`Team-level permissions: Admin`, `團隊級權限：管理員`],
  [`Team-level permissions: All`, `團隊級權限：全部`],
  [`Team-level permissions: Can edit`, `團隊級權限：可以編輯`],
  [`Team-level permissions: Can view`, `團隊級權限：可以查看`],
  [`Team-level permissions: No team permissions`, `團隊級權限：沒有團隊權限`],
  [`Team-level permissions: Owner`, `團隊級權限：創建者`],
  [`Team-level permissions`, `團隊級權限`],
  [`Teams`, `團隊`],
  [`Temperature`, `白平衡`],
  [`Templates`, `模板`],
  [`Text align bottom`, `下對齊`],
  [`Text align center`, `水平居中`],
  [`Text align justified`, `兩端對齊`],
  [`Text align left`, `左對齊`],
  [`Text align middle`, `垂直居中`],
  [`Text align right`, `右對齊`],
  [`Text align top`, `上對齊`],
  [`Text Styles`, `文本樣式`],
  [`Text tool`, `文本工具`],
  [`Text`, `文本`],
  [`The current document has unsaved changes. Figma will continue trying to save in the background. Please try again later.`, `當前文件有未儲存的更改。Figma 將在後台繼續嘗試儲存。請稍後再試。`],
  [`The document has unsaved changes. Reconnecting...`, `此文件有未儲存的改動。正在重新連接…`],
  [`The file browser allows you to navigate through your account. You can use it to access personal files, create and join teams, and connect with the wider Figma community.`, `檔案瀏覽器允許你在你的帳戶中進行瀏覽。你可以用它來訪問個人檔案，創建和加入團隊，並與更廣泛的 Figma 社群聯系。`],
  [`The following apps have been given permission to access your Figma files on your behalf. If you see any apps you're not expecting here, remove their permissions below.`, `以下應用程式已被授予代表你訪問 Figma 檔案的權限。如果你在這裡看到任何你不希望看到的應用程式，請在下面刪除其權限。`],
  [`The following fonts are not available, and need to be replaced in order to edit text.`, `以下字體不可用，需要被替換才能編輯文本。`],
  [`The properties and values of these variants are conflicting.                 Change the applied values on these variants to resolve this.`, `這些變體的屬性和值是衝突的。修改這些變體的應用值以解決這個問題。`],
  [`The properties and values of this variant are conflicting.                 Change the applied values on this variant to resolve this.`, `這個變體的屬性和值是衝突的。修改這個變體的應用值以解決這個問題。`],
  [`The selected variant is missing one or more properties.`, `選中的變體缺少一個或多個屬性。`],
  [`The selected variants are missing one or more properties.`, `選中的變體缺少一個或多個屬性。`],
  [`Their recent projects will appear here.`, `他們最近的項目將出現在這裡。`],
  [`There are more than 50 people working in this file right now, which can cause slowness. To keep things moving, we』ve temporarily turned off edit access and the ability to see other people』s cursors.`, `現在有超過50人在這個檔案中工作，這可能會導致速度變慢。為了保證進度，我們已經暫時關閉了編輯權限和查看其他人鼠標指針的功能。`],
  [`There are no published styles in your drafts.`, `你的草稿中沒有已發布的樣式。`],
  [`They』ll update instantly no matter what network you』re on and with no need to connect via USB.`, `無論你在什麼網絡上，它們都會立即更新，而且無需通過 USB 連接。`],
  [`This file has unsaved changes.`, `當前檔案有未儲存的更改。`],
  [`This file`, `當前檔案`],
  [`This is a Figma Community profile.`, `這是 Figma 社群的個人主頁。`],
  [`This is a Figma Community resource file.`, `這是一個 Figma 社群源檔案。`],
  [`This is the Figma Community, `, `這是 Figma 社群，`],
  [`This is the Figma Community.`, `這是 Figma 社群。`],
  [`This is your team space. From here you can add collaborators, manage permissions, and see all of your projects owned by the team.`, `這是你的團隊空間。在這裡，你可以添加合作者，管理權限，並查看團隊擁有的所有項目。`],
  [`This is your team's workspace. Create projects to help organize your files and invite members to your team to start collaborating. Click here to edit this description.`, `這是你的團隊工作空間。創建項目來幫助組織你的檔案，並邀請成員到你的團隊來開始協作。點擊這裡來編輯這個簡介。`],
  [`This person can still edit, because the file is set to allow editing by anybody with the link.`, `這個人仍然可以編輯，因為檔案被設定為任何有連結的人都可以編輯。`],
  [`This project doesn't have any files.`, `這個項目沒有任何檔案。`],
  [`This team is for Education users only. New users will be required to verify their Education status.`, `這個團隊只針對教育用戶。新用戶需要驗證其教育狀態。`],
  [`Thumbnail set`, `已設為封面`],
  [`Thumbnail size: 1920x960 (1600x960 safe area)`, `封面尺寸：1920x960（1600x960 安全區域）`],
  [`Tidy up`, `整理`],
  [`Tile`, `平鋪`],
  [`Tint`, `著色`],
  [`Title case`, `字首大寫`],
  [`to add to version history while editing.`, `來添加到版本歷史（編輯時）`],
  [`To confirm, please enter the name of the team.`, `確認刪除，請輸入團隊名稱。`],
  [`To create a component, select a layer and click the "Create component" button in the toolbar.`, `創建元件，請選擇一個層，然後單擊工具欄中的「創建元件」按鈕。`],
  [`to create your own plugin and manage any plugins currently in development.`, ` 來創建你自己的插件，以及管理在開發中的插件`],
  [`To delete a connection, click and drag on either end.`, `要刪除連接，請在任一端點單擊並拖動。`],
  [`To publish as a Team, move this file out of drafts and into a Team project.`, `如需以團隊身份發布，請將此檔案從草稿移動到團隊項目中。`],
  [`To view your frames live on your device, just download Figma Mirror on your`, `要在你的設備上實時查看你的畫框，只需在你的 `],
  [`Today`, `今天`],
  [`Tools`, `工具`],
  [`Top & Bottom`, `上 & 下`],
  [`Top and bottom`, `上下拉伸`],
  [`Top Center`, `頂部中間`],
  [`Top left corner radius`, `上左圓角半徑`],
  [`Top Left`, `上左`],
  [`Top padding`, `上邊距`],
  [`Top plugins`, `熱門插件`],
  [`Top right corner radius`, `上右圓角半徑`],
  [`Top Right`, `上右`],
  [`Top, right, bottom, and left padding can now be set independently.`, `現在可以獨立設定頂部、右側、底部和左側的邊距。`],
  [`Top`, `上`],
  [`Touch Down`, `觸摸按下`],
  [`Touch Up`, `觸摸離開`],
  [`Traditional Forms`, `傳統形式`],
  [`Transform`, `變形`],
  [`Trending`, `趨勢`],
  [`Triangle Arrow`, `三角箭頭`],
  [`Try Figma for free.`, `免費體驗 Figma`],
  [`Try Figma for free`, `免費體驗 Figma`],
  [`Try now`, `立即重試`],
  [`Type details`, `字體詳情`],
  [`Type something to start searching...`, `輸入點東西開始搜索…`],
  [`Type`, `類型`],
  [`Typography`, `字體排印`],
  [`Uh oh... we can't open that file`, `抱歉… 我們打不開那個檔案`],
  [`UI Design`, `UI 設計`],
  [`UI Kits`, `素材庫`],
  [`UI kits`, `素材庫`],
  [`Unable to follow this profile: You're already following this user`, `無法關注這個個人主頁：你已經關注這個用戶了`],
  [`Unable to install plugin. Please try again.`, `無法安裝插件，請重試。`],
  [`Unable to leave document`, `無法離開文件`],
  [`Unable to like this file: You already liked this file.`, `無法點贊這個檔案：你已經點贊過這個檔案了~`],
  [`Underline`, `下劃線`],
  [`Undo`, `撤銷`],
  [`Unfollow`, `取消關注`],
  [`Ungroup selection`, `取消群組所選項`],
  [`Ungroup`, `取消群組`],
  [`Uninstall`, `卸載`],
  [`Uninstalled`, `已卸載`],
  [`Union selection`, `連集所選項`],
  [`Unliked`, `已取消點贊`],
  [`Unlimited cloud storage`, `無限制的雲存儲`],
  [`Unlimited version history is available to paid teams.`, `付費的團隊可以使用無限的歷史版本`],
  [`Unlimited`, `無限制`],
  [`Unlink from styles to customize mixed contents.`, `取消連結樣式，可自定義多個內容。`],
  [`Unpublish`, `取消發布`],
  [`Unsupported file format`, `不支持的檔案格式`],
  [`Up to 15 characters (letters, numbers, or _)`, `最多 15 個字符（字母、數字或 _）`],
  [`Up to 2 editors`, `最多 2 個編輯者`],
  [`Update all`, `全部更新`],
  [`Update`, `更新`],
  [`Updates to components or styles`, `元件或樣式的更新`],
  [`Updates`, `更新`],
  [`Upgrade Figma plan`, `升級 Figma 計劃`],
  [`Upgrade now`, `馬上升級`],
  [`Upgrade plan`, `升級計劃`],
  [`Upgrade team`, `升級團隊`],
  [`Upgrade this team to publish components to the Team Library and use them across all files.`, `升級團隊，就可以將元件發布到團隊元件庫，且跨檔案使用。`],
  [`Upgrade to collaborate and share design libraries with your entire team.`, `升級以與你的團隊進行協作並共享設計元件庫。`],
  [`Upgrade to collaborate with more teammates`, `升級後可與更多隊友合作`],
  [`Upgrade to Organization`, `升級到組織版`],
  [`Upgrade to Professional`, `升級到專業版`],
  [`Upgrade to the Professional plan or to an Organization and get access to shared team libraries, advanced security features and`, `升級到專業版計劃或組織版，可以使用共享的團隊元件庫、高級安全功能以及`],
  [`Upgrade your plan to collaborate with more people and better organize your design files.`,`升級你的計劃後可以和更多人合作，更好的管理你的設計檔案`],
  [`Upgrade your plan to take full advantage of Figma.`, `升級你的計劃以充分利用 Figma 的優勢。`],
  [`Upgrade your plan`, `升級你的計劃`],
  [`Upgrade`, `升級`],
  [`Upper case`, `大寫`],
  [`Uppercase`, `大寫`],
  [`US$12 per editor/month`, `每個編輯者 12 美元/月`],
  [`Use as mask`, `設為遮罩`],
  [`Use Cases`, `使用案例`],
  [`Use Developer VM`, `使用開發者虛擬機`],
  [`Use libraries for quick access to components from other files.`, `使用庫可以快速訪問其他檔案中的元件。`],
  [`Use number keys for opacity`, `使用數字控制透明度`],
  [`Use shape outlines`, `使用形狀輪廓`],
  [`Use style`, `使用樣式`],
  [`Use the circular node to connect the selected object to another frame.`, `使用圓形節點將選定的對象連接到另一個畫框。`],
  [`Use the play button in the toolbar to play your prototype. If there are no connections, the play button can be used to play a presentation of your frames.`, `使用工具欄中的演示按鈕演示原型。 如果沒有連接，「演示」按鈕將演示你的畫框用於演示。`],
  [`UX Design`, `UX 設計`],
  [`Variants`, `變體`],
  [`Vector networks`, `向量網絡`],
  [`Vector`, `向量`],
  [`Version `, `版本 `],
  [`Version History `, `版本歷史 `],
  [`Version History`, `版本歷史`],
  [`Version history`, `版本歷史`],
  [`versions`, `版本`],
  [`Vertical Alternates and Rotation`, `豎排替代字形和旋轉`],
  [`Vertical Alternates`, `豎排替代字形`],
  [`Vertical direction`, `垂直方向`],
  [`Vertical Padding`, `垂直間距`],
  [`Vertical scrolling`, `垂直滾動`],
  [`Vertical`, `垂直`],
  [`Video tutorials`, `視頻教程`],
  [`View Community page`, `查看社群頁面`],
  [`View only`, `僅查看`],
  [`View page`, `查看頁面`],
  [`View Profile`, `查看個人主頁`],
  [`View`, `查看`],
  [`Viewer permission changed`, `查看者權限已修改`],
  [`Watch`, `手表`],
  [`We』re different from other design tools in some really special ways, so we』d like to take you through them.`, `我們和其他設計工具有一些非常特別的地方，所以我們想帶你了解一下。`],
  [`Web Design`, `網頁設計`],
  [`Web design`, `網頁設計`],
  [`Weight`, `字重`],
  [`Welcome to Figma Community!`, `歡迎來到 Figma 社群！`],
  [`Welcome to Figma!`, `歡迎來到 Figma！`],
  [`What』s New`, `新功能`],
  [`While clicking…`, `點擊時…`],
  [`While dragging from assets…`, `從資源面板拖動時…`],
  [`While dragging to select…`, `拖動並選中時…`],
  [`While editing a shape…`, `編輯形狀時…`],
  [`While hovering`, `當懸停時`],
  [`While moving…`, `移動時…`],
  [`While pointing…`, `指向時…`],
  [`While pressing`, `當按下時`],
  [`While resizing…`, `調整大小時…`],
  [`Whiteboards and Stickies`, `白板和貼紙`],
  [`who counts as an editor?`, `誰會被算做編輯者？`],
  [`Width – Scale down to fit width`, `寬度 - 縮小以適應寬度`],
  [`Width`, `寬`],
  [`will show up here as they become available.`, `可用時將顯示在這裡。`],
  [`Wireframes`, `線框圖`],
  [`Wireframing`, `線框圖`],
  [`Writing direction`, `書寫方向`],
  [`Writing Direction`, `書寫方向`],
  [`X-Offset`, `X 軸偏移`],
  [`Y-Offset`, `Y 軸偏移`],
  [`yesterday`, `昨天`],
  [`You are a verified Education user!`, `你已經認證為教育版用戶！`],
  [`You are currently the owner of `, `你目前是」`],
  [`You can always change this in Preferences.`, `你一直都可以在偏好設定中修改這個設定。`],
  [`You can favorite a project and it will be pinned under the team in the left sidebar.`, `你可以收藏一個項目，它就會固定在左側邊欄的團隊下面。`],
  [`You can head there by clicking on `, `你可以通過點擊 `],
  [`You can now edit files in any Education Team.`, `你可以在任何一個教育版團隊編輯檔案。`],
  [`You can update user permissions on the team page after setting up.`, `設定好後可以在團隊頁面更新用戶權限。`],
  [`You can't undo this action.`, `此操作不可撤銷。`],
  [`You don't have any connected apps`, `你沒有任何已連接的應用`],
  [`You don't have any deleted files.`, `沒有被刪除的檔案。`],
  [`You don't have any notifications.`, `暫無消息通知。`],
  [`You don't have any plugins installed`, `沒有已安裝的插件`],
  [`You don't have permission to remove files from this project.`, `你沒有權限從這個項目中移除這個檔案。`],
  [`You haven't published any plugins yet`, `你還沒有發布任何插件`],
  [`You will permanently lose all access to the projects and files in this team, and you cannot undo this action.`, `你將永久失去對該團隊中的項目和檔案的所有訪問權限，並且你無法撤銷此操作。`],
  [`You`, `你`],
  [`Your description was updated`, `你的簡介已更新`],
  [`Your file will soon be available for everyone in the Community to duplicate, remix, and share. Thanks for your contribution. You rock.`, `你的檔案很快就會被社群中的每個人複製、重新演繹和分享。感謝你的貢獻。你是最棒的。`],
  [`Your Instagram URL was updated`, `你的 Instagram 地址已更新`],
  [`Your location was updated`, `你的位置已更新`],
  [`Your new Community profile is live. View your profile to customize it. Everyone can now find you at:`, `你的社群個人主頁已經生效。查看你的個人主頁來自定義。所有人都能通過以下連結找到你：`],
  [`Your offline changes were synced`, `你的離線更改已同步`],
  [`Your profile is visible to the public at`, `大家可以在這裡看到你的個人主頁`],
  [`Your recent projects will appear here.`,`你最近的項目會出現在這裡。`],
  [`Your teams and favorited projects will appear here`, `你的團隊和收藏的項目將出現在這裡`],
  [`Your Twitter URL was updated`, `你的 Twitter 地址已更新`],
  [`Your Website URL was updated`, `你的網站地址已更新`],
  [`Zoom In`, `放大`],
  [`Zoom in`, `放大`],
  [`Zoom Out`, `縮小`],
  [`Zoom out`, `縮小`],
  [`Zoom to 100%`, `縮放至 100%`],
  [`Zoom to 200%`, `縮放至 200%`],
  [`Zoom to 50%`, `縮放至 50%`],
  [`Zoom to fit`, `縮放以適應大小`],
  [`Zoom to next frame`, `縮放至下一個畫框`],
  [`Zoom to previous frame`, `縮放至上一個畫框`],
  [`Zoom to selection`, `縮放至選中范圍`],
  [`Zoom/view Options`, `縮放/視圖選項`],
  [`Zoom`, `縮放`],
]


let MutationObserver = window.MutationObserver || window.WebKitMutationObserver;
let MutationObserverConfig = {
  childList: true,
  subtree: true,
  attributeFilter: ['data-label'],
  characterData: true
};

let observer = new MutationObserver(function (mutations) {
  let treeWalker = document.createTreeWalker(
    document.body,
    NodeFilter.SHOW_ALL,
    { 
        acceptNode: function (node) {
            if(node.nodeType === 3 || node.hasAttribute('data-label')) {
                return NodeFilter.FILTER_ACCEPT;
            }else {
                return NodeFilter.FILTER_SKIP;
            }
        } 
    },
    false
  );
  let dataMap = new Map();
  allData.forEach(([key, val]) => {
    if (key && !dataMap.has(key)) {
      dataMap.set(key, val);
    }
  });
  let currentNode = treeWalker.currentNode;
  while (currentNode) {
    if(currentNode.nodeType === 3) {
        let key1 = currentNode.textContent;
        if (dataMap.has(key1)) currentNode.textContent = dataMap.get(key1);
    }else {
        let key2 = currentNode.getAttribute('data-label');
        if (dataMap.has(key2)) currentNode.setAttribute('data-label', dataMap.get(key2));
    }

    currentNode = treeWalker.nextNode();
  }
});

observer.observe(document.body, MutationObserverConfig);
